### ISSUE TITLE
Not an issue, but a kind request :)

### ISSUE THREAD

**Issue by nnsense** [mike182uk/snpt#1]
Hi, I can't find where to ask a feature, I'll post it here, please feel free to move/delete it as appropriate.
A very simple request: I use your program during ssh sessions, and it seems I can't copy into clipboard (which makes sense).
Would it be possible to have the content of the snippet directly on screen? Pretty much as a `snpt write <snippetID> && cat *snippetFileName` could do.
Well, I'm here, why not ask another little thing.. ;)
Do you think could be possible to add a switch, like "-q" for example (yes, as in dockers..) to show only the snippet id and use it in a command, for example modifying ls behavious when called with an snippetID: `snpt ls -q <snippetID>` : dd401ee5affc4069e45c8f463864cf2ed3ac2c85
Both these features are possible using awk, sed, cut and so on but would be great having it natively.

Thanks, thanks, thanks :)

**Comment by mike182uk** [comment]
Hey @nnsense 

The first one should be something easy that we can get added. 

As for the second thing, what is your use case for this? If your passing the snippetID to the command already (`snpt ls -q <snippetID>`) why would you want to then get the same thing back?

Or maybe i have misunderstood your intentions here?

**Comment by nnsense** [comment]
You're right, I've messed up with the example! 😄 

Say you're looking for a snippet to write:

    $> snpt ls | grep Reference.md
    Reference.md - PHP Reference [3512e0e0b11771fab3c9cc632b69d71f60de3233]
    Reference.md - c Reference [dd401ee5affc4069e45c8f463864cf2ed3ac2c85]
    Reference.md - C# Reference [a56513a83e2ad5cd30ab0ccafb4b1a5dcf27102d]
    Reference.md - VBS Reference [f2822ce5412404e94a64b05d76f00c89a8436243]

To write it out, here you need to grab your mouse, select and copy the snipped ID and paste it in the next command:

    $> snpt write a56513a83e2ad5cd30ab0ccafb4b1a5dcf27102d

What I'm thinking is like:

    $> snpt ls | grep Reference.md
    Reference.md - PHP Reference [3512e0e0b11771fab3c9cc632b69d71f60de3233]
    Reference.md - c Reference [dd401ee5affc4069e45c8f463864cf2ed3ac2c85]
    Reference.md - C# Reference [a56513a83e2ad5cd30ab0ccafb4b1a5dcf27102d]
    Reference.md - VBS Reference [f2822ce5412404e94a64b05d76f00c89a8436243]

    $> snpt ls -q "c Reference"
    dd401ee5affc4069e45c8f463864cf2ed3ac2c85

So then you can use it like:

    $> snpt write $(snpt ls -q "c Reference")

**Comment by nnsense** [comment]
Hey! Thank you for the print function!!  👍

**Comment by mike182uk** [comment]
No probs, it was quite easy to add in and could actually be quite useful. As for the for the q flag, I will need to have a think about how we could do this. At the moment the problem I’m seeing is that 2 different snippets could technically have the same name so snpt would need to prompt to ask which one you wanted, which would not work for your use case. 


- Mike

**Comment by nnsense** [comment]
Actually, I wouldn't mind, if the user is using the same name AND the same description is really too much to deal with, I would just thrown an error for multiple snippets found, the use case of this would be very peculiar so I think who's going to use it knows what is doing.
I'm currently using the following in my bashrc to avoid IDs:

	function snpts() {
	snpts=$(snpt ls | grep "$1" | egrep -wo '\w{40}')
	if [[ $(wc -w <<< $snpts) > 1 ]]; then echo 'Multiple snippets found'; else snpt print $snpts;fi
	}

But would be great having this already "on board" :D

**Comment by nnsense** [comment]
I've forgotten to close the issue.. a couple of years ago. Thanks for your help ;)
