### ISSUE TITLE
Error with cp when using snippetId parameter

### ISSUE THREAD

**Issue by examinedliving** [mike182uk/snpt#14]
Works fine if I use `cp` with no arguments and select from index, but if I enter an id (tried with and without brackets), I get the following error:

`TypeError: _lodash2.default.findWhere is not a function`
    `at onStdinBuffered (...path to npm....\npm\node_modules\snpt\lib\find-snippet.js:51:40)`
   `at process._tickCallback (internal/process/next_tick.js:103:7)`
    `at Function.Module.runMain (module.js:449:11)`
    `at startup (node.js:148:18)`
    `at node.js:405:3`

On Windows 7 if that matters.

**Comment by mike182uk** [comment]
Hy @examinedliving, thanks for reporting this. I've fixed the bug and released a new version `0.0.4` (so you will need to uninstall and re-install to get the changes).

Looks like `findWhere` was removed from `lodash` at some point.

Let me know if your still having problems :)
